name: flutter_base
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  dio: ^5.4.0
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.3
  intl: ^0.18.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  scroll_to_index: ^3.0.1
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.6.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.3
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  firebase_core: ^2.24.2
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.0.7
  animations: ^2.0.11
  smooth_page_indicator: ^1.1.0
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  app_settings: ^5.1.1
  hive_flutter: ^1.1.0
  permission_handler: ^11.1.0
  share_plus:
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  path: ^1.8.3
  flutter_widget_from_html: ^0.15.1




dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.1
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/app_icon.png"
  image_path_ios: "assets/app_icon.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/svgs/
    - assets/images/
    - assets/langs/

  fonts:
    - family: en
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
    - family: text
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: italic
      fonts:
        - asset: assets/fonts/Raleway-Italic.ttf
    - family: ar
      fonts:
        - asset: assets/fonts/cairo.ttf

